// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Suppress internal member warning for VaultRust.instance which is the
// idiomatic FRB pattern for accessing the initialized instance.

/// FRB function to initialize the encrypted database connection.
Future<void> initializeVault({
  required String dbPath,
  required String encryptionKey,
}) => VaultRust.instance.api.crateApiSimpleInitializeVault(
  dbPath: dbPath,
  encryptionKey: encryptionKey,
);

/// FRB function to securely save a new memory fragment.
Future<void> saveMemory({required String content}) =>
    VaultRust.instance.api.crateApiSimpleSaveMemory(content: content);
